### ISSUE TITLE
Allow to edit oligos

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#109]
I find it handy to be able to edit the sequence and name of the oligos in the oligo page. Do you think this could be implemented?

This would entail rechecking assemblies after editing or establishing some constraints i.e. allow only modifications on unused oligos or, if the oligo is used, only allow to modify the name.

I'm sure you've put some thoughts into this so, what do you think?

**Comment by manulera** [comment]
I decided not to allow it for the reasons you point out (need to check, etc) since it has only two fields. However, I agree that users probably expect to have it. I will add it next! Thanks for trying it!
