### ISSUE TITLE
Source numbers are not reset after deleting sources

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#110]
When adding different sources, deleting all of them and then adding more, the numbers keep increasing instead of being reset to 1 (see screen capture). Is this the expected behavior or a bug?

<img width="575" alt="Screenshot 2024-03-10 at 14 16 13" src="https://github.com/manulera/ShareYourCloning_frontend/assets/10668217/c5eb25b8-35c5-42da-bc4f-9c020179cefd">

**Comment by dgruano** [comment]
Reopening due to weird behaviour:

(1) When a source with ID < maxID is deleted, the "gap" is not filled with new sources (this may be the intended behavior)
(2) When all sources are deleted, ID is -Infinite (bug)

![Issue110](https://github.com/manulera/ShareYourCloning_frontend/assets/10668217/f7c3ced6-a046-4f5d-8bfc-1de445bf5f6b)

**Comment by manulera** [comment]
Wow that's a funny catch! I will fix it.

Regarding the max, I think it's fine like this. That's more similar to how a database id would work.

**Comment by manulera** [comment]
Fixed now with #117

Thank you @dgruano
