### ISSUE TITLE
PCR submit button should be hidden until oligos are selected

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#120]
As the title says, I think the submit button should be hidden until the PCR input form is properly filled with all the input values (in this case, the oligos). This is already the behaviour of other source types like the Repository Source. Otherwise, a "Field required"  error could be displayed, like currently happens when the source is a "Manual input" but the user did not type anything.

**Comment by manulera** [comment]
This is now closed! Thanks @dgruano
