### ISSUE TITLE
App crashes when selecting a different "Template sequence" when "Insert sequence" is empty (Homologous recombination source)

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#124]
When I create an homologous recombination source from another source, this one will fill in the field "Template sequence". However, if I make a mistake and I start the HR source from the "insert", I have to change that. Doing so with an empty "Insert sequence" field makes the app crash, raising `Uncaught TypeError: Cannot read properties of undefined (reading 'id')``

See video for reference:

![Screen Recording 2024-03-22 at 21 32 44](https://github.com/manulera/ShareYourCloning_frontend/assets/10668217/d2dd665d-9fa1-4223-9897-64f8b56dec73)

**Comment by manulera** [comment]
Thanks @dgruano for noticing. I have added a fix. Still the UI is not great, but it will have until a good solution is found for the data model as mentioned in https://github.com/manulera/ShareYourCloning_backend/issues/102
