### ISSUE TITLE
Minimap to visualize large histories

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#195]
When creating a complex history tree, some sources may go out of the page. For these cases, it would be useful to have a minimap with an overview of the content and a square highlighting the current view. This would be even better if the minimap is interactive and the highlighting square can be dragged around to navigate the page.

Examples of this functionality I can think of are imageJ (when you zoom on an image) or the Pubmed Central figure viewer.

Some libraries that could be use to accomplish this are:
https://github.com/antoniojps/react-simple-minimap
https://github.com/jeremy-carbonne/react-minimap

**Comment by manulera** [comment]
This could be a bit tricky, but it would be cool. Something I have also been considering is to allow to hide part of the history(you could click on a sequence and hide the upstream history.
