### ISSUE TITLE
Enable cmd + X things

### ISSUE THREAD

**Issue by manulera** [manulera/ShareYourCloning_frontend#204]
Now the editor overrides many shortcuts!

**Comment by dgruano** [comment]
Can we add other shortcuts?

- `Cmd + F` to search
- `Esc` to close the search dialog or the active selection

No sure whether this has to be done within SYC or OVE

**Comment by manulera** [comment]
Hi @dgruano the goal of this issue was actually to remove all the overrides that OVE set in place by default (ctrl + P for printing, Ctrl + F for finding, etc.). I disabled all of them. The reason was because even when you were in a different tab in the interface (not only on `Sequence` tab), the shortcuts were overriden. Perhaps it's worth enabling at least the search on the `Sequence` tab (via OVE config). You would have to change the main editor properties when changing to that tab as shown here:

https://github.com/TeselaGen/tg-oss/issues/86#issuecomment-2221664437

Then, when clicking on a different tab, unset the shortcuts.
