### ISSUE TITLE
Copy reverse complement when a reverse oligo or feature is selected

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#216]

**Comment by dgruano** [comment]
Also, when searching for a sequence, if this is found on the reverse strand, OVE displays the orientation. When clicking and copying this selection, the reverse complement should be the one copied (this would be a weird use case, but I'd say it's the cleanest).

**Comment by manulera** [comment]
Hi @dgruano not sure about this one.

I see that for reverse primers, both SnapGene and Benchling copy the reverse strand, but for reverse features Snapgene copies the top strand. I was actually a bit surprised that the reverse was copied when the feature was reversed.

I think I would rather keep the behaviour as is, and with #217 it should be obvious what you have copied. Maybe the toast can even say copied top strand or something like that.

As for the search, I don't think that's a very relevant use-case given that if you found the sequence via search, you probably already have that sequence in your clipboard?

**Comment by dgruano** [comment]
Okay! I agree that we can make it very clear with the toast, either by indicating what sequence was copied or the actual sequence.

For the search, I agree it's a very rare use case. I can only imagine it if the user search for a sequence with mismatches and copies the search result, as it would be different than the one in the clipboard.
