### ISSUE TITLE
Alert user before deleting a used source

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#267]
I think it would be handy to prevent or alert the user when they are about to delete a source that is being used downstream in the cloning strategy. This could be done in different ways:
- Similar to the small text indicating that a primer cannot be deleted if it is being used.
- Displaying a modal for the user to confirm their choice.

This is related to my comment on collapsed copied sources in #260

**Comment by manulera** [comment]
I added this
