### ISSUE TITLE
Prepopulate "Enzyme" field in MoClo templates

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#271]
I assume such cloning kits are designed to be digested with a particula enzyme, and I thought It would be useful to have it already filled in the Restriction/Ligation source input:

<img width="376" alt="image" src="https://github.com/user-attachments/assets/a5b17812-59df-4a26-8a4d-eb26f38b56e2">

**Comment by manulera** [comment]
I have thought of this but was a bit lazy about implementing it. The templates are generated from spreadsheets, and the spreadsheet could include an extra field for it. I will make an issue in the template repo.
