### ISSUE TITLE
Display frontend and backend commit version IDs

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#280]
Since we are pushing changes to the production site on the go, it might be nice for developers to see what is the current production version. I don't know if we can currently check this, so I was thinking of displaying it on the top bar (two links with the hashes for frontend and backend), or add a new element in the "About" dropdown saying "Version" and displaying the info inside a modal. What do you think?

**Comment by manulera** [comment]
Yes, actually I am working on this at the moment for the integration with eLabFTW. I am trying to see what the best way of doing this would be. For the backend perhaps it's better to publish to pypi instead of using the source code. I have to check

**Comment by manulera** [comment]
Now you can see it also in the frontend at https://shareyourcloning.org/ At about > App version
