### ISSUE TITLE
Should we create a different tab for Primer Designer?

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#315]

**Comment by dgruano** [comment]
Now I see why the original title was silly: when using the Primer Designer, we may want to look at a different sequence. So, @manulera have you considered adding a new tab? What are the pros/cons?

**Comment by manulera** [comment]
The reason is that having two main editors slows the app massively. Maybe there is a clever way to memoize components for them not to slow down each other, but I did not figure out how.
