### ISSUE TITLE
Primer designer cannot be used to add non-palindromic restriction sites

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#316]
Thinking of the specific case of Golden Gate, with a Type IIS enzyme (let's say, BsaI), the orientation of the recognition sequence matters, as the site is non-palindromic:
```
5'-GGTCTCN!NNNNN-3'
3'-CCAGAGNNNNN¡N-5'
   ______
recognition upstream of cut

5'-N!NNNNNGAGACC-3'
3'-NNNNN¡NCTCTGG-5'
          ______
recognition downstream of the cut
```

With the current implementations, both non-palindromic sites will have the same orientation, and both can be changed if the "Amplification direction" changes from "forward" to "reverse". 

We should allow the user to select the orientation of each individual non-palindromic site.

Note: the current workaround is to do this in two steps:
1. Amplify template with fw oligo that adds a site in the desired orientation, and a rv oligo that does not add bases.
2. Amplify the resulting sequence with the opposite orientation, with fw oligo that adds a site in the desired orientation, and a rv oligo that does not add bases.
3. (extra) Change the last fw oligo name to rv to avoid confusion

Note 2: What you called "Amplification direction", in my opinion, should be called "Template orientation"

**Comment by manulera** [comment]
Good point, I have to allow for the orientation to be selected
