### ISSUE TITLE
Feature selection from parent sources is incorrect in Gateway example

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_frontend#318]
When selecting a part of the sequence in the result of the LR reaction from the Gateway example, it appear to select the wrong origin sequences from the parents. As you can see in the example screenshot, I selected the Topaz YFP in the resulting plasmid and the selections from the parents are incorrect:
1. There is a selection in both parents, while the Topaz YFP only comes from one of them.
2. The sequence selected spans the AmpR cassette instead of the actual TopazYFP.

![Screenshot from 2024-12-09 09-18-30](https://github.com/user-attachments/assets/aa095b5d-9704-4361-abd5-b68469365e00)

I am not familiar with how the selection of sequence origins is enabled. Is this bug specifit to the LR Gateway reaction?

**Comment by manulera** [comment]
Good catch! No, it's just an assembly like all the others so it should work. Will look into it now
